# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default           # Specifies the Default agent pool
  demands: agent.name -equals nodejs  # Ensures the pipeline runs on the 'nodejs' agent

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '12.16.1'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
